[buildPlans.AureliusRound]
family = "Aurelius Round"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.AureliusRound.variants.design]
one = "base"
two = "curly-neck-serifless"
four = "open-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
zero = "slashed"
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-extended"
g = "single-storey-earless-corner"
i = "serifed-flat-tailed"
j = "serifed"
k = "curly-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck2"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
underscore = "above-baseline"
caret = "medium"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "et-toothless-corner"
at = "compact"
dollar = "through"
percent = "rings-continuous-slash"

[buildPlans.AureliusRound.variants.italic]
one = "base"
two = "curly-neck-serifless"
four = "open-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
zero = "slashed"
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "serifed"
k = "cursive-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck2"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-bottom-serifed"
underscore = "above-baseline"
caret = "medium"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "et-toothless-corner"
at = "compact"
dollar = "through"
percent = "rings-continuous-slash"

[buildPlans.AureliusRound.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.AureliusRound.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.AureliusRound.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AureliusRound.widths.Normal]
shape = 600
menu = 5
css = "normal"
