[buildPlans.AureliusRound]
family = "Aurelius Round"
spacing = "terminal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.AureliusRound.variants.design]
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "open-serifless"
five = "upright-arched-serifless"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-earless-corner"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
capital-eszet = "rounded-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-eth = "curly-bar"
lower-delta = "flat-top"
capital-lambda = "straight-serifless"
lower-lambda = "tailed-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "flat-top"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "et-tailed"
at = "compact"
dollar = "through"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"

[buildPlans.AureliusRound.variants.italic]
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "open-serifless"
five = "upright-arched-serifless"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
h = "straight-serifless"
i = "flat-tailed"
j = "flat-hook-serifless"
k = "cursive-serifless"
l = "flat-tailed"
m = "serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifed"
capital-eszet = "rounded-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-eth = "curly-bar"
lower-delta = "flat-top"
capital-lambda = "straight-serifless"
lower-lambda = "tailed-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "flat-top"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "curly"
guillemet = "straight"
number-sign = "upright"
ampersand = "et-tailed"
at = "compact"
dollar = "through"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"

[buildPlans.AureliusRound.weights.Regular]
shape = 350
menu = 350
css = 350

[buildPlans.AureliusRound.weights.Bold]
shape = 750
menu = 750
css = 750

[buildPlans.AureliusRound.widths.Normal]
shape = 600
menu = 5
css = "normal"
