[buildPlans.AureliusRound]
family = "Aurelius Round"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.AureliusRound.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed"
a = "double-storey-toothless-corner"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "flat-tailed"
j = "flat-hook-serifless"
k = "cursive-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-eth = "curly-bar"
lower-delta = "flat-top"
capital-lambda = "straight-serifless"
lower-lambda = "tailed-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "flat-top"
zero = "tall-slashed"
one = "base"
two = "curly-neck"
three = "two-arcs"
four = "open-non-crossing"
five = "upright-arched"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "lower-open"
at = "compact"
dollar = "through"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"

[buildPlans.AureliusRound.variants.italic]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-flat-bottom-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed"
a = "double-storey-toothless-corner"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-flat-hook-earless-rounded"
h = "tailed-serifless"
i = "flat-tailed"
j = "flat-hook-serifless"
k = "cursive-bottom-right-serifed"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-tailed-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-flat-hook-serifless"
z = "cursive"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-eth = "curly-bar"
lower-delta = "flat-top"
capital-lambda = "straight-serifless"
lower-lambda = "tailed-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "flat-top"
zero = "tall-slashed"
one = "base"
two = "curly-neck"
three = "two-arcs"
four = "open-non-crossing"
five = "upright-arched"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "lower-open"
at = "compact"
dollar = "through"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"

[buildPlans.AureliusRound.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.AureliusRound.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.AureliusRound.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.AureliusRound.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.AureliusRound.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AureliusRound.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AureliusRound.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.AureliusRound.widths.Extended]
shape = 720
menu = 7
css = "expanded"
